### ISSUE TITLE
module signing

### ISSUE THREAD

**Issue by BrianHicks** [asteris-llc/converge#16]
GPG signing, so we need from the CLI both a way to obtain and trust a key and a way to verify signatures. We're not going to be *making* the signatures, but documentation on how to do so should be provided.

**Comment by BrianHicks** [comment]
90% sure this got in. @ajhager could you close if so?

**Comment by ajhager** [comment]
Closed by 7d12847e4321e621358435db3547ad4502b1d98a

**Comment by BrianHicks** [comment]
Whoo!
