### ISSUE TITLE
How should we manage module docs and examples?

### ISSUE THREAD

**Issue by rebeccaskinner** [asteris-llc/converge#173]
The `shell` modules has a file `bad_rm.hcl` which illustrates how the module manages situations where a command fails.  This isn't exactly a `sample`, nor is it really a sample error that should go in `samples/errors` instead it's illustrating a specific feature of the shell module.  Currently there's not a good place for it- or other similar examples- to live, nor a general location for handling module-specific documentation.  We should understand how we want to handle this.

**Comment by BrianHicks** [comment]
This is now in `examples`, which are fully worked examples. The best place for the specific situation of a feature of a module is in the module documentation.
