### ISSUE TITLE
ability to wait for a condition

### ISSUE THREAD

**Issue by ryane** [asteris-llc/converge#238]
In https://github.com/asteris-llc/converge-elk/blob/master/elk.hcl#L46, I am abusing `task.query` to wait for a service to become healthy. Should this be a native capability of converge?

It it could behave similarly to `task.query` (or possibly `healthcheck`) but with a built-in retry loop and timeout. Perhaps something like:

```hcl
task.probe "elasticsearch-health" {
   check = "[[ $(curl -s 'http://localhost:9200/_cluster/health' 2>/dev/null | jq -r .status) == \"green\" ]]"
   initialDelay = "1s"
   interval = "1s"
   timeout = "10s"
}
```

**Comment by ryane** [comment]
Just thinking aloud - perhaps we start with something like `wait.query` that would be similar to the `task.probe` example above. That would be the escape hatch so that you can roll your own wait conditions using existing tools. In the future, we could build higher-level waits like `wait.port`, `wait.url`, `wait.docker.healthcheck`, `wait.host`, etc.

**Comment by BrianHicks** [comment]
We probably should begin with that and `wait.port`. Unless there's a really easy way to check if a port is open and in use by some program? (`lsof` could do it but I'm not sure how portable that invocation would be)

**Comment by ryane** [comment]
you could also use `nc` but of course you would have to ensure it is installed first. but, yeah, wait.port seems pretty fundamental

**Comment by BrianHicks** [comment]
It's kind of like having to write a curl command to download a file every time. It's "good enough" but eventually you want #250
