### ISSUE TITLE
Execution Engine Ignoring Warning Levels

### ISSUE THREAD

**Issue by Dacode45** [asteris-llc/converge#243]
If a fatal error happens during a check or apply I do the following. 
```go
if err != nil {
			t.Status = &resource.Status{
				WarningLevel: resource.StatusFatal,
				Status:       err.Error(),
			}
			return t.Status, err
```
When I run `converge plan` expecting to see an error I get the following output
```
root/systemd.unit.test:
	Messages:
	Has Changes: no
	Changes: No changes
```

**Comment by rebeccaskinner** [comment]
@Dacode45 was this the issue that you fixed in: 38588118e47f753ebbea74ac40f9edf998aa2f7c ?  If not can you validate that it's still a problem?
