### ISSUE TITLE
named locks

### ISSUE THREAD

**Issue by BrianHicks** [asteris-llc/converge#249]
A named lock would be nice for doing things that affect the whole system, but which Converge currently does in parallel. (Like package management using `apk` on Alpine)

**Comment by BrianHicks** [comment]
Let's let the implementor worry about exactly how to implement this and change the issues tags around to reflect it's ready. I'd like whoever does this to prefer to store the data in the graph somehow (generated dependencies) if possible. Otherwise, a named mutex probably will work just fine.

**Comment by sehqlr** [comment]
Could we have the lock be a resource type?
```
lock "yum" {
  // config on lock
}

task "install nginx" {
  check = ".."
  apply = ".."
  depends = ["lock.yum"]
}
```

**Comment by BrianHicks** [comment]
It would probably have to be inside the task, since the goal is to synchronize across multiple modules.

**Comment by ryane** [comment]
now known as "group" - see #392
