### ISSUE TITLE
file download/fetch module

### ISSUE THREAD

**Issue by BrianHicks** [asteris-llc/converge#250]
A file download module would be nice.

``` hcl
file.fetch "consul.zip" {
  source = "https://releases.hashicorp.com/consul/0.6.4/consul_0.6.4_linux_amd64.zip"
  destination = "/tmp/consul.zip"
  hash sha256 = "abdf0e1856292468e2c9971420d73b805e93888e006c76324ae39416edcf0627"
}
```

**Comment by BrianHicks** [comment]
I think this stands as specced, with one change: if no destination is specified, the file should be buffered in memory/to a temp file on disk. It can then be referenced from other modules.

**Comment by BrianHicks** [comment]
@Dacode45 could you finish your work on systemd before assigned yourself new tasks, please?

**Comment by arichardet** [comment]
#543

**Comment by automaticgiant** [comment]
would it make more sense to make a separate resource for generic release download, or extend fetch, to provide something like the [goss packer provisioner](https://github.com/YaleUniversity/packer-provisioner-goss):
```
file.fetch goss {
  version = "0.3.2"
  arch = "amd64"
  os = "{{platform.OS}}" # platform.ARCH would be nice
  url = "https://github.com/aelsabbahy/goss/releases/download/vVERSION/goss-OS-ARCH"
  downloadPath = "/tmp/goss-VERSION-OS-ARCH"
  remote_folder = "/tmp"
  remote_path = "/tmp/goss"
}
```
