### ISSUE TITLE
add conditionals to module resource

### ISSUE THREAD

**Issue by BrianHicks** [asteris-llc/converge#268]
module resource should have conditional evaluation. Something like this:

```hcl
module "x.hcl" "x" {
  when = [
    "eq {{system.os}} \"darwin\""
  ]
}
```

If the whens combine (with and) to false, the subtree rooted at the module is dropped from evaluation.

**Comment by BrianHicks** [comment]
This still makes sense a couple of days later… mostly. The string syntax for the conditionals is too different from the rest of our configuration. A better syntax could look llike:

```hcl
module "x.hcl" "x" {
  when equal ["{{system.os}}", "darwin"]
}
```

To generalize: a `when` block will have a string for the operator, then the operator's arguments. These arguments could take pretty much any shape, depending on the operator.

@sehqlr this syntax might be useful for your param validation work as well?

**Comment by stevendborrelli** [comment]
when "{{ system.os == "darwin" }}" ?

**Comment by sehqlr** [comment]
Yes, this would be useful for parameters. I like the basic idea, but I
think the syntax will be tricky.

**Comment by BrianHicks** [comment]
Right, whiteboard discussion in the office over. We're going to go forward with something like a switch construct that will be expanded like a macro (that is, it will not be evaluated at runtime, but before and pruned.)

```hcl
select { // or `switch` or `select!` or `switch!`... You get the idea.
  case {
    conditional = "some syntax goes here"
    value = {
      module "x.hcl" "x" {}
    }
  }
}
```

If the conditional syntax ends up being within a string, we can move that to the path selector of `case` and get rid of `value`.

Preferred syntax among the group was something like `"platform.os == 'darwin'"` (Or so I remember; @stevendborrelli and @rebeccaskinner can you confirm)? At any rate, we want to *not* use all of text/template here because are "bob" or similar strings true or false?

**Comment by rebeccaskinner** [comment]
PR #362
