### ISSUE TITLE
better status display on plan and execution

### ISSUE THREAD

**Issue by BrianHicks** [asteris-llc/converge#269]
We have the following constraints:
- provide reasonable status to the operator to let them know the program has not frozen
- remove that status from the logs. Logs should only have actionable information!

My proposal: dynamically write a list to stdout. The list is the time the currently executing modules have been running and which are executing. Once the operation is complete, the list is erased. It updates every second otherwise. Something like:

```
root/module.a/task.do-the-thing: 10s
root/module.b/task.install-docker: 52s
```

Let the bikeshedding commence!

**Comment by ryane** [comment]
I would definitely like something like this. wondering how the erase part would look when launched from another tool like vagrant or terraform. Maybe it would look fine but, if not, maybe we just write new lines when not running in an interactive (not sure if this is correct right terminology) session?

**Comment by BrianHicks** [comment]
I was thinking that if we're in an interactive session we'll lower the status output lines to DEBUG, but keep them at INFO if we're in a non-interactive session like those you mentioned.

**Comment by BrianHicks** [comment]
In short, this is a UI affordance for interactive terminals. No more, no less.

**Comment by BrianHicks** [comment]
Next steps before we remove i-want-a-pony: someone should mock up how this will look in a motion format. I've got a good idea of how to do it, but if anyone gets the gumption to go ahead, do it!

**Comment by BrianHicks** [comment]
How about something like https://gist.github.com/55644a2f2452dce57f0e2a95632f43dd ?

Recording: https://asciinema.org/a/7k6kkoycjj36tk27akt81db3g

**Comment by stevendborrelli** [comment]
LGTM
