### ISSUE TITLE
Can we simplify the visualization of large modules?

### ISSUE THREAD

**Issue by BrianHicks** [asteris-llc/converge#280]
When rendered, big modules looks more complicated than they really are. (example from @ryane)

![elk](https://cloud.githubusercontent.com/assets/355401/18673099/1bef2e9a-7f10-11e6-89cb-36c834b31a1f.png)

What can we do to make these look better? Maybe we could omit the edges between a module and its direct children? As long as they stay in the same box it's still pretty clear.

**Comment by rebeccaskinner** [comment]
We can label the boxes with the module name without having it be a node with arrows- I think there was an earlier iteration of the graphs where we were doing that- it shouldn’t be too hard.
