### ISSUE TITLE
We're using too many ports

### ISSUE THREAD

**Issue by BrianHicks** [asteris-llc/converge#286]
We're assigned port 4774 right now. We were using 2693/2694 before. We could probably mux on 4774 for HTTP or RPC (by looking at the session establishment headers.) We should probably do that, and then we'd only have one port open for everything.

**Comment by BrianHicks** [comment]
We probably just need to stick https://github.com/soheilhy/cmux in front of everything.

**Comment by leonardogcsoares** [comment]
The code is a bit overwhelming at first, but with slight orientation I think I can do this! Cmux seems the perfect solution. =D

**Comment by BrianHicks** [comment]
Woohoo! I've got a code sample if you like for a similar project: https://gist.github.com/902891350f3e7e13bf03966183c3db74

The cmux readme is a little out of date, that's up-to-date as of this morning. Happy to help clear up any questions you have on the Converge Slack: http://converge-slack.aster.is

**Comment by BrianHicks** [comment]
@leonardogcsoares are you still working on this? Can we help in any way?
