### ISSUE TITLE
binary distribution

### ISSUE THREAD

**Issue by ryane** [asteris-llc/converge#306]
Currently the terraform and vagrant provisioners depend on release binaries stored on bintray. See https://github.com/ChrisAubuchon/terraform-provisioner-converge/issues/1#issuecomment-248457022. The distribution of these binaries should be added to the release process.

**Comment by stevendborrelli** [comment]
@ryane can we close this now that an install script is available in the main repo? 

I'm already using it with our terraform provisioner fork.

**Comment by ryane** [comment]
yep
