### ISSUE TITLE
Handle time.Duration in Preparer

### ISSUE THREAD

**Issue by arichardet** [asteris-llc/converge#358]
At some point, a date in ISO 8601 will need to be accepted for a field for the user module. This may be useful for other modules, so we probably want to handle this in the preparer.

**Comment by BrianHicks** [comment]
How about this?

```
type Blah struct {
	Timeout    time.Duration `hcl:"timeout"`
	ExpiryDate time.Time     `hcl:"time"`
}
```

if the parser hits a `time.Duration` it will parse it with `time.ParseDuration` and expose the error (if any) to the user.

If the parser hits a `time.Time`, it will parse it as "YYYY-MM-DDThh:mm:ssz". If that fails, it will try parsing as "YYYY-MM-DD" and set the time of day to zero and the timezone to the system timezone.

**Comment by arichardet** [comment]
Yes, that seems to make sense.

**Comment by arichardet** [comment]
Closing this issue for the implementation of time.Duration. Opening issue #490 to handle adding time.Time.
