### ISSUE TITLE
values that don't implement Stringer log badly

### ISSUE THREAD

**Issue by BrianHicks** [asteris-llc/converge#398]
If you have a value that doesn't implement stringer, the logs will print the value as `%!s(<value>)`. This doesn't look good. We should change the log printer to use the `%v` verb instead, except in cases where `Stringer` is implemented and errors (`errors.Wrap` gives a stacktrace when printed with `%v` that makes it look like Converge is panicking)

**Comment by vikashvverma** [comment]
@BrianHicks I want to work on this. Can you give me a head start?

**Comment by BrianHicks** [comment]
@vikashvverma sure! The code in question is at https://github.com/asteris-llc/converge/blob/master/helpers/logging/formatter.go#L159

You'll basically need to:

- change to use `"%v"` instead of `%q` if `f.fancy` is false
- change to use `%v` otherwise
- test with a wrapped error to make sure the stack trace is not printed (sample value: `errors.Wrap(errors.New("test"), "wrapped")` should produce `wrapped: test` if printed with `%s`, and a stacktrace if printed with `%v`.)

Feel free to ask any questions here or [in the Slack](http://converge-slack.aster.is/). :)
