### ISSUE TITLE
pass typed params through to modules

### ISSUE THREAD

**Issue by ryane** [asteris-llc/converge#409]
It would be helpful to be able to pass list params (or map, bool, or any param types we support) as-is through to modules. Currently, this doesn't work:

containerModule.hcl:

```
param "image" {}
param "tag" {}
param "name" {}
param "ports" {
  default = []
}

docker.image "image" {
  name = "{{param `image`}}"
  tag  = "{{param `tag`}}"
}

docker.container "container" {
  name    = "{{param `name`}}"
  image   = "{{param `image`}}:{{param `tag`}}"
  ports   = ["{{param `ports`}}"]
  force   = true
}
```

runContainer.hcl

```
module "containerModule.hcl" "elasticsearch" {
  params = {
    name  = "elasticsearch"
    image = "elasticsearch"
    tag   = "2.4.0"
    ports = ["127.0.0.1:9200:9200"]
  }
}
```

When the preparer for the docker container resource is populated, the value for ports is `[]string{"[127.0.0.1:9200:9200]"}` which is not what we want. We want `[]string{"127.0.0.1:9200:9200"}`.

**Comment by rebeccaskinner** [comment]
This appears to be working as of commit # d0fef40501c952445f6022dbbf9e001c5af3b3ef
