### ISSUE TITLE
user/group not activating changes

### ISSUE THREAD

**Issue by stevendborrelli** [asteris-llc/converge#417]
Tested with 0.3.0-beta2 from the release page on linux:

Using the `samples/group.hcl` and `samples/user.hcl`, no user or group are created. 

```
root/user.group.group:
 Messages:
 Has Changes: no
 Changes: No changes

Summary: 0 errors, 0 changes

```

**Comment by arichardet** [comment]
The problem is that 0.3.0-beta2 was a mac osx cross compile. A linux build, linux cross compile, or werker cross compile work.
