### ISSUE TITLE
file.mode error when file does not exist

### ISSUE THREAD

**Issue by ryane** [asteris-llc/converge#491]
When Check runs in the file.mode resource, it will set an error and set the Status to fatal if the target file does not exist. If there are any dependencies on the file.mode resource, they will also return `Error: error in dependency "root/file.mode.render"` errors.

However, it seems like a common use case to have file.mode target a file that is created by another converge task. You may see lots of errors from the plan but applying the same hcl may work perfectly fine. This is confusing.

Thoughts on what the correct behavior should be? Maybe we don't set the status to fatal and just add a message the the file does not (yet) exist?

**Comment by stevendborrelli** [comment]
Yes, it seems like we should have a warn (not fail) in the check phase for certain tasks in plan.

**Comment by arichardet** [comment]
+1
