### ISSUE TITLE
unarchive resource

### ISSUE THREAD

**Issue by ryane** [asteris-llc/converge#513]
consider adding a resource that makes it easier to extract files from tar, tar.gz, and zip files.

idea for a minimal implementation:

```hcl
file.unarchive "etcd" {
  source      = "/tmp/etcd.tar.gz" # or https://github.com/coreos/etcd/releases/download/v3.0.14/etcd-v3.0.14-linux-amd64.tar.gz
  destination = "/usr/local/bin/"
  owner       = "root"
  group       = "root"
}
```

**Comment by rebeccaskinner** [comment]
closed in #592

**Comment by automaticgiant** [comment]
any ideas to make it idempotent?

**Comment by rebeccaskinner** [comment]
There's not a good way to ensure it's idempotent without keeping a registry of the archives and their checksums.  For a lot of formats, e.g. tar, you can get a list of files pretty easily, but you'd still ned to extract the archive to get checksums for each of the files; at that point there's not much value in calculating the checksum and only copying over the file if it differs.  We might be able to make check more useful but we'd need to have some way to deal with changes of remote resources between plan and apply.  We'd talked about having check generate a database that would be used for execution apply, if all resources were fetched at check time and serialized into that a database we could make some guarantees there.

**Comment by automaticgiant** [comment]
i've rewritten my unarchive invocation of concern as:
```
task untgz_converge {
  check = "[ {{lookup `file.fetch.converge.destination`}} -ot {{param `bin`}}converge ]"
  apply = "tar xzm -C {{platform.OS}}/ -f {{platform.OS}}/.archives/converge.tgz converge"
}
```
thanks for the thoughts
