### ISSUE TITLE
Manage part of files

### ISSUE THREAD

**Issue by loa** [asteris-llc/converge#568]
When using Ansible/Chef/Puppet I try to strictly stick to package install, create config file and start/manage service. But sometimes it's very hard since you need to manage part of a file, ex add DNS to _ifcfg-*_ files.

[Ansible lineinfile](http://docs.ansible.com/ansible/lineinfile_module.html) is great for this and saved me multiple times _(it's not perfect but so much better than all other sed solutions I seen...)_.

It would also be nice to improve on this design by allowing multiple lines instead of single lines.

[Ansible blockinfile](https://docs.ansible.com/ansible/blockinfile_module.html) solves some of the multiple lines situations, but sadly some files ex `/etc/environment` [don't support comments](http://unix.stackexchange.com/questions/97736/escape-hash-mark-in-etc-environment).

Very exciting to see where converge will be going 👍

**Comment by stevendborrelli** [comment]
Thanks for your feedback! We're adding this to our roadmap.
