### ISSUE TITLE
Go get to install doesn't work on macOS

### ISSUE THREAD

**Issue by rafaelmagu** [asteris-llc/converge#619]
Hi there,

I just happened across this project and was keen to have a go (no pun intended), but the installation documentation wasn't very helpful.

Trying to `go get github.com/asteris-llc/converge` gave me this on a freshly-formatted, up-to-date macOS Sierra setup:

```
$ go get github.com/asteris-llc/converge

package github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api: no buildable Go source files in /Users/rafael/code/go/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api
```

I'm a newbie to Go in general, so I can't figure out why this is failing.

**Comment by BrianHicks** [comment]
Interesting! It seems like there's a bug somewhere. It'd probably be easiest if you [download a pre-built release](https://github.com/asteris-llc/converge/releases) to get started.

**Comment by gawbul** [comment]
See the issue here https://github.com/grpc-ecosystem/grpc-gateway/issues/331 for details on this
